package database.test.gui;

import java.awt.Font;
import javax.swing.table.TableModel;

public class GenericTableWindow 
        extends javax.swing.JFrame {

    public GenericTableWindow() {
        this(null);
    }

    public GenericTableWindow(TableModel dataModel) {
        this.initComponents();
        this.setColorTheme();
        this.setTableModel(dataModel);
    }

    public void setTableModel(TableModel dataModel) {
        if (dataModel != null) {
            table.setModel(dataModel);
            table.setFont(Const.FONT_DEFAULT_12);
            table.getTableHeader().setFont(Const.FONT_DEFAULT_12);
            table.setRowHeight(20);
            table.updateUI();
        }
    }

    private void setColorTheme() {
        table.setSelectionBackground(Const.COLOR_HIGHLIGHT_BG);
        table.setSelectionForeground(Const.COLOR_HIGHLIGHT_FG);
        table.setGridColor(Const.COLOR_TABLE_GRID);
    }

    //<editor-fold defaultstate="collapsed" desc="GUI Code: Automatically Generated by NetBeans">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        table_scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_scrollPane.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(table_scrollPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable table;
    private javax.swing.JScrollPane table_scrollPane;
    // End of variables declaration//GEN-END:variables

    //</editor-fold>
}
