package database.test.gui;

import database.test.DatabaseManager;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class LoginWindow
        extends javax.swing.JFrame {

    private DatabaseManager database = null;
    private LoginListener loginListener = null;

    /**
     * Create a new LoginWindow that is used to log in to a database.
     *
     * @param loginListener The object to be notified if the login success.
     * @param database The database to log in to.
     */
    public LoginWindow(LoginListener loginListener, DatabaseManager database) {
        // initializes the components
        this.initComponents();
        this.initListeners();
        this.setLocationRelativeTo(null);
        this.setColorTheme();

        this.loginListener = loginListener;
        this.database = database;

        this.setTitle(Const.WIN_TITLE_LOGIN + " - " + Const.APP_TITLE);
        this.setLogo();
        this.clear();

        // TODO: [TESTING] remove this part in the final product
        tbxUsername.setText("owner");
        tbxPassword.setText("admin");
        // ===========================================
    }

    /**
     * Try logging in to the database. Notify the listener if success,
     * otherwise, warn the user.
     */
    public void submit() {
        if (database == null || loginListener == null) {
            warningText.setText("Something went wrong. Please restart the application.");
            System.exit(-1);
        }
        database.setUsername(tbxUsername.getText().trim());
        database.setPassword(new String(tbxPassword.getPassword()));
        if (database.connect()) {
            this.clear();
            loginListener.login();
        } else {
            warningText.setText("Incorrect username and/or password.");
            tbxUsername.requestFocus();
        }
    }

    //<editor-fold defaultstate="collapsed" desc="GUI Code: Custom Initialization and Methods">
    /**
     * Clear all the data in the window.
     */
    public void clear() {
        tbxUsername.setText("");
        tbxPassword.setText("");
        warningText.setText(" ");
        tbxUsername.requestFocus();
    }

    private void setLogo() {
        // TODO: make the logo change according to user's settings
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                Const.PATH_TO_LOGO_IMAGE)));
    }

    private void setColorTheme() {
        this.getContentPane().setBackground(Const.COLOR_LOGIN_WINDOW_BG);
        panel_logo.setBackground(Const.COLOR_LOGIN_WINDOW_BG);

        tbxUsername.setSelectionColor(Const.COLOR_HIGHLIGHT_BG);
        tbxUsername.setSelectedTextColor(Const.COLOR_HIGHLIGHT_FG);
        tbxPassword.setSelectionColor(Const.COLOR_HIGHLIGHT_BG);
        tbxPassword.setSelectedTextColor(Const.COLOR_HIGHLIGHT_FG);

        warningText.setForeground(Const.COLOR_ERROR_TEXT);
    }

    private void initListeners() {
        btnLogin.addActionListener((ActionEvent) -> {
            this.submit();
        });

        KeyAdapter enterKeySubmit = new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    submit();
                }
            }
        };

        tbxPassword.addKeyListener(enterKeySubmit);
        tbxUsername.addKeyListener(enterKeySubmit);
    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="GUI Code: Automatically Generated by NetBeans">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_logo = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        javax.swing.JLabel l_user = new javax.swing.JLabel();
        javax.swing.JLabel l_pass = new javax.swing.JLabel();
        tbxUsername = new javax.swing.JTextField();
        tbxPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        warningText = new javax.swing.JLabel();
        javax.swing.JLabel placeholder1 = new javax.swing.JLabel();
        javax.swing.JLabel placeholder2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(400, 360));
        setMinimumSize(new java.awt.Dimension(400, 360));
        setPreferredSize(new java.awt.Dimension(400, 360));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 360));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel_logo.setBackground(new java.awt.Color(255, 255, 255));

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_logoLayout = new javax.swing.GroupLayout(panel_logo);
        panel_logo.setLayout(panel_logoLayout);
        panel_logoLayout.setHorizontalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_logoLayout.setVerticalGroup(
            panel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 16, 0);
        getContentPane().add(panel_logo, gridBagConstraints);

        l_user.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        l_user.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_user.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(l_user, gridBagConstraints);

        l_pass.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        l_pass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_pass.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(l_pass, gridBagConstraints);

        tbxUsername.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbxUsername.setText("root");
        tbxUsername.setPreferredSize(new java.awt.Dimension(28, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(tbxUsername, gridBagConstraints);

        tbxPassword.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbxPassword.setText("admin");
        tbxPassword.setPreferredSize(new java.awt.Dimension(41, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(tbxPassword, gridBagConstraints);

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setMaximumSize(new java.awt.Dimension(128, 36));
        btnLogin.setMinimumSize(new java.awt.Dimension(128, 36));
        btnLogin.setName(""); // NOI18N
        btnLogin.setPreferredSize(new java.awt.Dimension(128, 36));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        getContentPane().add(btnLogin, gridBagConstraints);
        btnLogin.getAccessibleContext().setAccessibleDescription("");

        warningText.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        warningText.setForeground(new java.awt.Color(255, 0, 0));
        warningText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningText.setText("Incorrect username and/or password.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 8, 8);
        getContentPane().add(warningText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(placeholder1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        getContentPane().add(placeholder2, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel panel_logo;
    private javax.swing.JPasswordField tbxPassword;
    private javax.swing.JTextField tbxUsername;
    private javax.swing.JLabel warningText;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

    public interface LoginListener {

        /**
         * Called when the user has logged in successfully (and is now connected
         * to the database) through the LoginWindow. The application should hide
         * the LoginWindow and display the main window after this.
         */
        void login();
    }

}
