package database.test.gui;

public class ManageProductsWindow
        extends javax.swing.JFrame {

    /**
     * Creates new form EditCustomerInfoWindow.
     */
    public ManageProductsWindow() {
        this.initComponents();
        this.initListeners();
        this.setLocationRelativeTo(null);
        this.setColorTheme();

        this.setTitle("" + " - " + Const.APP_TITLE);
    }

    //<editor-fold defaultstate="collapsed" desc="GUI Code: Custom Initialization and Methods">
    private void setColorTheme() {

    }

    private void initListeners() {

    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="GUI Code: Automatically Generated by NetBeans">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_header = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        chkFiltering = new javax.swing.JCheckBox();
        javax.swing.JLabel l_filterCat = new javax.swing.JLabel();
        cbxCategory = new javax.swing.JComboBox<>();
        javax.swing.JLabel l_filterStatus = new javax.swing.JLabel();
        cbxStatus = new javax.swing.JComboBox<>();
        btnFilterRefresh = new javax.swing.JButton();
        tableProducts_scrollPane = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();
        btnNewProduct = new javax.swing.JButton();
        btnRenameProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 350));
        setSize(new java.awt.Dimension(520, 540));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel_header.setBackground(new java.awt.Color(255, 255, 255));
        panel_header.setLayout(new java.awt.GridBagLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        headerLabel.setText("Products");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 16, 8, 16);
        panel_header.add(headerLabel, gridBagConstraints);

        chkFiltering.setBackground(new java.awt.Color(255, 255, 255));
        chkFiltering.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        chkFiltering.setSelected(true);
        chkFiltering.setText("Enable Filtering:");
        chkFiltering.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 8);
        panel_header.add(chkFiltering, gridBagConstraints);

        l_filterCat.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        l_filterCat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_filterCat.setText("Category:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 4);
        panel_header.add(l_filterCat, gridBagConstraints);

        cbxCategory.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cbxCategory.setMinimumSize(new java.awt.Dimension(128, 22));
        cbxCategory.setPreferredSize(new java.awt.Dimension(128, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        panel_header.add(cbxCategory, gridBagConstraints);

        l_filterStatus.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        l_filterStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_filterStatus.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 16, 4, 4);
        panel_header.add(l_filterStatus, gridBagConstraints);

        cbxStatus.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available for Sale", "Discontinued", "(Both)" }));
        cbxStatus.setMinimumSize(new java.awt.Dimension(128, 22));
        cbxStatus.setPreferredSize(new java.awt.Dimension(128, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        panel_header.add(cbxStatus, gridBagConstraints);

        btnFilterRefresh.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnFilterRefresh.setText("Refresh");
        btnFilterRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilterRefresh.setMaximumSize(new java.awt.Dimension(128, 36));
        btnFilterRefresh.setMinimumSize(new java.awt.Dimension(128, 36));
        btnFilterRefresh.setName(""); // NOI18N
        btnFilterRefresh.setPreferredSize(new java.awt.Dimension(96, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 12, 4, 8);
        panel_header.add(btnFilterRefresh, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        getContentPane().add(panel_header, gridBagConstraints);

        tableProducts.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Stock Quantity", "Current Unit Price"
            }
        ));
        tableProducts.setGridColor(new java.awt.Color(204, 204, 204));
        tableProducts.setRowHeight(20);
        tableProducts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableProducts_scrollPane.setViewportView(tableProducts);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        getContentPane().add(tableProducts_scrollPane, gridBagConstraints);

        btnNewProduct.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnNewProduct.setText("New Product...");
        btnNewProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewProduct.setMaximumSize(new java.awt.Dimension(128, 26));
        btnNewProduct.setMinimumSize(new java.awt.Dimension(128, 26));
        btnNewProduct.setName(""); // NOI18N
        btnNewProduct.setPreferredSize(new java.awt.Dimension(128, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 8, 4);
        getContentPane().add(btnNewProduct, gridBagConstraints);

        btnRenameProduct.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnRenameProduct.setText("Edit Selected Product Info...");
        btnRenameProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRenameProduct.setMaximumSize(new java.awt.Dimension(196, 26));
        btnRenameProduct.setMinimumSize(new java.awt.Dimension(196, 26));
        btnRenameProduct.setName(""); // NOI18N
        btnRenameProduct.setPreferredSize(new java.awt.Dimension(196, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 8, 4);
        getContentPane().add(btnRenameProduct, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilterRefresh;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnRenameProduct;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxStatus;
    private javax.swing.JCheckBox chkFiltering;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel panel_header;
    private javax.swing.JTable tableProducts;
    private javax.swing.JScrollPane tableProducts_scrollPane;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
